services:
  - type: web
    name: bbj-church-backend
    env: java
    region: oregon
    plan: free
    buildCommand: cd backend && mvn clean package -DskipTests
    startCommand: java -jar backend/target/bbj-church-manager-1.0.0.war
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: PORT
        value: 8080
      - key: JDBC_DATABASE_URL
        value: mysql://nrMPj1ECajN3NtY.root:LSTkYzHVTdplnF2X@gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/bbj
      - key: JDBC_DATABASE_USERNAME
        value: nrMPj1ECajN3NtY.root
      - key: JDBC_DATABASE_PASSWORD
        value: LSTkYzHVTdplnF2X
      - key: B2_KEY_ID
        value: 0055be753f9e33f0000000001
      - key: B2_KEY_NAME
        value: Project
      - key: B2_BUCKET_NAME
        value: bbj1532
