services:
  - type: web
    name: bbj-church-manager
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      # Database Configuration - TiDB Cloud
      - key: ENVIRONMENT
        value: production
      - key: DB_URL
        value: jdbc:mysql://gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/bbj?useSSL=true&serverTimezone=UTC
      - key: DB_USERNAME
        value: nrMPj1ECajN3NtY.root
      - key: DB_PASSWORD
        value: dFkBlyj7CjtmqK08
      # B2 File Upload Service Credentials
      - key: B2_KEY_ID
        value: 5be753f9e33f
      - key: B2_APP_KEY
        value: K005uAur9WX0YGfPwOwbdyCsVwKOhuA
      - key: B2_BUCKET_NAME
        value: bbj-church-media


